### ISSUE TITLE
live example app down?

### ISSUE THREAD

**Issue by mschilli87** [PaulC91/shinyauthr#42]
The [live example app](https://cultureofinsight.shinyapps.io/shinyauthr/) linked in the README returns a 404 for me.

**Comment by PaulC91** [comment]
Yes sorry, I don't have control over that shinyapps.io account anymore or a personal server so there is no hosted example. I'll remove it from the readme. 

If you have the package installed you can launch the example yourself with `shinyauthr::runShinyExample()`

**Comment by mschilli87** [comment]
Allright. Thanks for the prompt response.
Kinda unrelated: Would you still recommend using this package for a new project given that it doesn't seem to be getting much love recently? :wink:
If not, would you have any pointers to more actively maintained alternatives.
I'd hate to re-invent the wheel, especially with something a sensitive as authentication.

**Comment by PaulC91** [comment]
Depends if you are looking for additional features? 

I recently had a pull request to add the option of cookie based logins, so that will be a feature soon. 

I try to add additional features if requested and they don't require much work, but I personally don't use this package anymore for auth (I use shinyproxy for deployment with auth0 authentication at my job now). However, it is quite a simple package and therefore does not require much maintenance or active development.

It does seem like a lot of people are using this package though so I do plan to submit to CRAN at some point.

Another option would be [shinymanager](https://github.com/datastorm-open/shinymanager) which I think was inspired by shinyauthr and has added additional things like an admin mode. I have never used it but it looks good.

Another couple auth options for single shiny apps that I am aware of but haven't used either:

https://github.com/Tychobra/polished
https://github.com/curso-r/auth0
